version: "3.1"

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 9090:80

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: danubio
      WORDPRESS_DB_PASSWORD: o3P3>I2VI]*r
      WORDPRESS_DB_NAME: site
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: site
      MYSQL_USER: danubio
      MYSQL_PASSWORD: o3P3>I2VI]*r
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./db:/var/lib/mysql

volumes:
  wordpress:
  db:
